AllCops:
  Exclude:
    - 'app/views/**/*.slim'
    - 'app/views/**/**/*.slim'

Style/Documentation:
  Enabled: false

##################### Metrics ##################################

Layout/LineLength:
  Max: 110

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200
